# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: # Replace with a single Patreon username
liberapay: jrowe
# worthy of love
custom: ['https://www.eff.org', 'https://apache.org', 'https://www.lls.org']
