liberapay: jrowe # ideally would use this open source account
buy_me_a_coffee: jrowe # but going with the flow
# worthy of love
custom: ['https://www.eff.org', 'https://apache.org', 'https://www.lls.org']
