# reminder if you change this file, restart the server process.
#
# Global site settings {{ site.** }}

title: James Rowe
author: James Rowe
email: jrowe6720@gmail.com
description: >- # mutli line capable
  The digital journal of James Rowe. Something between wordpress, livejournal and gists.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jsrowe.com" # https://jsr6720.com -> https://jsr6720.github.io

# if you sense a theme.. RIT college assigned me a user id of "jsr6720" and it stuck
twitter_username: jrowe6720
github_username:  jsr6720
linkedin_username: jsr6720

# Build settings

# update semver major if changing url param
# todo consider using collections one day
permalink: /:title/ # :output_ext meh(?)

# flip to true to push /archive/ folder to web server. warning doesn't show up in rest of site
collections:
  archive:
    output: false
    permalink: /:collection/:name

theme: minima
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/