# reminder if you change this file, restart the server process.
#
# Global site settings {{ site.** }}

title: James' Thoughts
author: James Rowe
email: jrowe6720@gmail.com
# add it to header for url sharing
logo: /jsr6720-github-io-repo-social-preview.png
description: >- # mutli line capable
  The digital journal of James Rowe. Something between WordPress, LiveJournal and gists.
baseurl: "" # the subpath of your site, e.g. /blog
# TODO aws redirect https://jsr6720.com -> https://jsr6720.github.io
url: "https://www.jsrowe.com" # backup --> github pages --> "https://jsr6720.github.io"
rss: feed.xml

# if you sense a theme.. RIT assigned me a user id of "jsr6720" and it stuck
# see [who-am-i.md](https://github.com/jsr6720/jsr6720.github.io/blob/main/_archive/2024-05-21-who-am-i.md)
twitter_username: jrowe6720
github_username:  jsr6720
linkedin_username: jsr6720
bluesky_username: jsr6720

# Build settings

# todo consider using collections one day
permalink: /:title/

# using collections to keep content in this repo but away from published site
# but linkable back via github hosting
collections:
  archive: # not everything written should stay published eh?
    output: false
    permalink: /:collection/:name
  whitepapers: # see [/_whitepapers/README.md](https://github.com/jsr6720/jsr6720.github.io/blob/main/_whitepapers/README.md)
    output: false
    permalink: /:collection/:name
  recipes: # todo something fun
    output: false
    permalink: /:collection/:name

theme: minima # base install
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc

# toc settings
toc:
  min_level: 1
  max_level: 3
  list_class: toc__list
  sublist_class: toc__sublist

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
