# reminder if you change this file, restart the server process.
#
# Global site settings {{ site.** }}

title: James' Thoughts
author: James Rowe
email: jrowe6720@gmail.com
description: >- # mutli line capable
  The digital journal of James Rowe. Something between wordpress, livejournal and gists.
baseurl: "" # the subpath of your site, e.g. /blog
# aws redirect https://jsr6720.com -> https://jsr6720.github.io
url: "https://jsr6720.github.io" # one day update to https://www.jsrowe.com

# if you sense a theme.. RIT assigned me a user id of "jsr6720" and it stuck
# see who-am-i.md for more
twitter_username: jrowe6720
github_username:  jsr6720
linkedin_username: jsr6720

# Build settings

# update semver major if changing url param
# todo consider using collections one day
permalink: /:title/ # :output_ext meh(?)

# using collections to keep content in this repo but away from published site
# but linkable back via github hosting
collections:
  archive: # not everything written should stay published eh?
    output: false
    permalink: /:collection/:name
  whitepapers: # see readme in _whitepapers
    output: false
    permalink: /:collection/:name

theme: minima # base install
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/