# reminder if you change this file, restart the server process.
#
# Global site settings {{ site.** }}

title: James Rowe
author: James Rowe
email: jrowe6720@gmail.com
description: >- # mutli line capable
  The digital journal of James Rowe. Something between wordpress, livejournal and gists.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jsr6720.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jrowe6720
github_username:  jsr6720
linkedin_username: jsr6720

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
