name: AWS Role Connection Check

on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  CheckAWSConnection:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GHA_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Verify AWS Identity
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          if [ "$ACCOUNT_ID" != "058264284723" ]; then
            echo "Error: Connected to unexpected AWS account"
            exit 1
          fi
          echo "Successfully verified AWS connection to account $ACCOUNT_ID"